name: Создание SEO-страниц для фильмов

on:
  workflow_dispatch:
  push:
    paths:
      - "movies_updates.json"
      - "tools/generate_seo_pages.py"

permissions:
  contents: write

jobs:
  generate-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Получить доступ к репозиторию
        uses: actions/checkout@v4

      - name: Настройка Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Создание статических SEO-страниц
        run: python tools/generate_seo_pages.py

      - name: Сгенерированные страницы
        run: |
          git config user.name "seo-pages-bot"
          git config user.email "actions@github.com"

          git add film sitemap.xml
          git diff --cached --quiet && echo "Нет изменений" || git commit -m "Создать SEO-страницы"

          git pull --rebase origin main
          git push origin main
