name: Update best movies list 5000

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-movies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Update movies_updates.json
        env:
          TMDB_READ_TOKEN: ${{ secrets.TMDB_READ_TOKEN }}
          KINOPOISK_API_KEY: ${{ secrets.KINOPOISK_API_KEY }}
          TARGET_COUNT: "5000"
          GKM_CAST_LIMIT: "80"
        run: |
          python tools/update_movies_updates.py
          python tools/merge_movies_updates_to_data.py
          python tools/update_cast_cache.py
      - name: Commit changes
        run: |
          git config user.name "movie-updater-bot"
          git config user.email "movie-updater-bot@users.noreply.github.com"
          git add movies_updates.json data/index.json data/*.json
          git diff --cached --quiet || git commit -m "Update best movies list 5000"
          git push
